#version: "3.7"

x-log-basic: &basic-log
  logging:
    driver: "json-file"
    options:
      max-size: "1m"
      max-file: "3"
      labels: "system"

x-common: &common
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "50M"
    restart: unless-stopped
    <<: *basic-log

x-backend: &backend
    <<: *common
    image: mvkvl/api-backend:0.0.1-gin
    env_file:
      - .env.backend


services:

  disco:
    <<: *common
    image: slinkgo/disco:0.0.9
    container_name: disco
    ports:
      - "127.0.0.1:8771:8081"
      - "127.0.0.1:8772:8082"
    env_file:
      - .env.disco

  eureka:
    image: mvkvl/eureka-server
    container_name: eureka-server
    stop_grace_period: "2s"
    environment:
      - "EUREKA_SERVICE_LOGIN=eureka"
      - "EUREKA_SERVICE_PASSWORD=eureka"
#      - "ROOT_LOGGING_LEVEL=WARN"
#      - "CUSTOM_LOGGING_LEVEL=WARN"
#      - "EUREKA_SERVICE_PORT=8761"
#      - "EUREKA_SERVICE_HOSTNAME=localhost"
    ports:
      - "127.0.0.1:8761:8761"
    <<: *basic-log

  backend-a1-gin:
    <<: *backend
    container_name: backend-a-1
    environment:
      - "SERVICE_NAME=service-a"
      - "INSTANCE_ID=1"
    ports:
      - "3111:3000"
      - "3112:3001"
  backend-a2-gin:
    <<: *backend
    container_name: backend-a-2
    environment:
      - "SERVICE_NAME=service-a"
      - "INSTANCE_ID=2"
    ports:
      - "3121:3000"
      - "3122:3001"
  backend-a3-gin:
    <<: *backend
    container_name: backend-a-3
    environment:
      - "SERVICE_NAME=service-a"
      - "INSTANCE_ID=3"
    ports:
      - "3131:3000"
      - "3132:3001"
  backend-a4-gin:
    <<: *backend
    container_name: backend-a-4
    environment:
      - "SERVICE_NAME=service-a"
      - "INSTANCE_ID=4"
    ports:
      - "3141:3000"
      - "3142:3001"
  backend-b1-gin:
    <<: *backend
    container_name: backend-b-1
    environment:
      - "SERVICE_NAME=service-b"
      - "INSTANCE_ID=1"
    ports:
      - "3211:3000"
      - "3212:3001"
  backend-b2-gin:
    <<: *backend
    container_name: backend-b-2
    environment:
      - "SERVICE_NAME=service-b"
      - "INSTANCE_ID=2"
    ports:
      - "3221:3000"
      - "3222:3001"

  gateway-fiber:
    deploy:
      resources:
        limits:
          memory: "50M"
    image: mvkvl/api-gateway-fiber:0.0.1
    container_name: gateway-fiber
    environment:

      - "GATEWAY_NAME=GW-FIBER"
      - "SERVICE_PORT=3000"
      - "MONITORING_PORT=3001"
      - "GO_ENV=dev"

#      - "EUREKA_URL=http://eureka:8761/eureka"
      - "EUREKA_LOGIN=eureka"
      - "EUREKA_PASSWORD=eureka"
      - "EUREKA_HEARTBEAT_INTERVAL=5s"
      - "EUREKA_REFRESH_INTERVAL=10s"

      - "DISCO_URL=http://disco:8081"
      - "DISCO_LOGIN=disco"
      - "DISCO_PASSWORD=disco"
      - "DISCO_HEARTBEAT_INTERVAL=5s"
      - "DISCO_REFRESH_INTERVAL=10s"

#      - "STATIC_REGISTRY_FILE=/conf/registry.yml"

      - "REGISTRY_REFRESH_INITIAL_DELAY=2s"
      - "REGISTRY_REFRESH_INTERVAL=10s"

#      - "RATE_LIMIT_RPM=150"

      - "LOGGING_LEVEL_ROOT=DEBUG"
#      - "LOGGING_LEVEL_HEADER_AUTH_PROVIDER=TRACE"
#      - "LOGGING_LEVEL_EUREKA_CLIENT=TRACE"
      - "LOGGING_LEVEL_DISCO_CLIENT=TRACE"
      - "LOGGING_LEVEL_DISCOVERY_REGISTRY=TRACE"
#      - "LOGGING_LEVEL_SERVICE_RESOLVER=TRACE"
#      - "LOGGING_LEVEL_FIBER_GATEWAY=TRACE"
    volumes:
      - ./routes:/conf
    restart: unless-stopped
    ports:
      - "3011:3000"
      - "3012:3001"
    <<: *basic-log
  gateway-gin:
    deploy:
      resources:
        limits:
          memory: "50M"
    image: mvkvl/api-gateway-gin:0.0.1
    container_name: gateway-gin
    environment:

      - "GATEWAY_NAME=GWB-GIN"
      - "SERVICE_PORT=3000"
      - "MONITORING_PORT=3001"
      - "GO_ENV=dev"

#      - "EUREKA_URL=http://eureka:8761/eureka"
      - "EUREKA_LOGIN=eureka"
      - "EUREKA_PASSWORD=eureka"
      - "EUREKA_HEARTBEAT_INTERVAL=5s"
      - "EUREKA_REFRESH_INTERVAL=10s"

      - "DISCO_URL=http://disco:8081"
      - "DISCO_LOGIN=disco"
      - "DISCO_PASSWORD=disco"
      - "DISCO_HEARTBEAT_INTERVAL=5s"
      - "DISCO_REFRESH_INTERVAL=10s"

#      - "STATIC_REGISTRY_FILE=/conf/registry.yml"

      - "REGISTRY_REFRESH_INITIAL_DELAY=2s"
      - "REGISTRY_REFRESH_INTERVAL=10s"

      - "RATE_LIMIT_RPM=150"

      - "LOGGING_LEVEL_ROOT=INFO"
#      - "LOGGING_LEVEL_HEADER_AUTH_PROVIDER=TRACE"
#      - "LOGGING_LEVEL_EUREKA_CLIENT=TRACE"
#      - "LOGGING_LEVEL_DISCO_CLIENT=TRACE"
#      - "LOGGING_LEVEL_DISCOVERY_REGISTRY=TRACE"
#      - "LOGGING_LEVEL_SERVICE_RESOLVER=TRACE"
#      - "LOGGING_LEVEL_FIBER_GATEWAY=TRACE"
    volumes:
      - ./routes:/conf
    restart: unless-stopped
    ports:
      - "3021:3000"
      - "3022:3001"
    <<: *basic-log


  gateway-cloud:
    image: mvkvl/cloud-gateway
    container_name: cloud-gateway
    restart: unless-stopped
    stop_grace_period: "2s"
    environment:
      - "SERVER_PORT=8080"
      - "SERVICE_NAME=cloud-gateway"
      - "EUREKA_DEFAULT_ZONE=http://eureka:eureka@eureka:8761/eureka"
    volumes:
      - ./routes:/conf
    ports:
      - "127.0.0.1:9993:8080"
    <<: *basic-log
#  eureka-client:
#    image: mvkvl/eureka-client
#    container_name: eureka-client
#    restart: unless-stopped
#    stop_grace_period: "2s"
#    environment:
#      - "CLIENT_SERVER_PORT=8080"
#      - "CLIENT_SERVICE_NAME=eureka-client"
##      - "EUREKA_DEFAULT_ZONE=http://eureka:8761/eureka"
#      - "EUREKA_DEFAULT_ZONE=http://eureka:eureka@eureka:8761/eureka"
#    ports:
#      - "127.0.0.1:9990:8080"
#    <<: *basic-log
