#version: "3.7"

x-log-basic: &basic-log
  logging:
    driver: "json-file"
    options:
      max-size: "1m"
      max-file: "3"
      labels: "system"

services:

  gateway-fiber:
    deploy:
      resources:
        limits:
          memory: "50M"
    image: mvkvl/api-gateway-fiber:0.0.1
    container_name: api-gateway-fiber
    environment:

      - "SERVICE_PORT=3000"
      - "GO_ENV=dev"

      - "EUREKA_URL=http://eureka:8761/eureka"
      - "EUREKA_LOGIN=eureka"
      - "EUREKA_PASSWORD=eureka"
      - "EUREKA_HEARTBEAT_INTERVAL=5s"
      - "EUREKA_REFRESH_INTERVAL=10s"

      - "DISCO_URL=http://disco:8080"
      - "DISCO_LOGIN=disco"
      - "DISCO_PASSWORD=disco"
      - "DISCO_HEARTBEAT_INTERVAL=5s"
      - "DISCO_REFRESH_INTERVAL=10s"

#      - "STATIC_REGISTRY_FILE=/conf/registry.yml"

      - "REGISTRY_REFRESH_INITIAL_DELAY=2s"
      - "REGISTRY_REFRESH_INTERVAL=10s"

      - "RATE_LIMIT_RPM=150"

      - "LOGGING_LEVEL_ROOT=DEBUG"
#      - "LOGGING_LEVEL_HEADER_AUTH_PROVIDER=TRACE"
#      - "LOGGING_LEVEL_EUREKA_CLIENT=TRACE"
      - "LOGGING_LEVEL_DISCO_CLIENT=TRACE"
      - "LOGGING_LEVEL_DISCOVERY_REGISTRY=TRACE"
#      - "LOGGING_LEVEL_SERVICE_RESOLVER=TRACE"
#      - "LOGGING_LEVEL_FIBER_GATEWAY=TRACE"
    volumes:
      - ./routes:/conf
    restart: unless-stopped
    ports:
      - "3003:3000"
      - "3004:3001"
    <<: *basic-log

  backend:
    deploy:
      resources:
        limits:
          memory: "50M"
    image: mvkvl/api-backend:0.0.1
    container_name: api-backend
    environment:
      - "EUREKA_URL=http://eureka:8761/eureka"
      - "EUREKA_LOGIN=eureka"
      - "EUREKA_PASSWORD=eureka"
      - "EUREKA_HEARTBEAT_INTERVAL=5s"
      - "EUREKA_REFRESH_INTERVAL=10s"
      - "DISCO_URL=http://disco:8080"
      - "DISCO_LOGIN=disco"
      - "DISCO_PASSWORD=disco"
      - "LOGGING_LEVEL_ROOT=DEBUG"
    restart: unless-stopped
    ports:
      - "3101:3101"
      - "3102:3102"
      - "3103:3103"
      - "3201:3201"
      - "3202:3202"
      - "3203:3203"
    <<: *basic-log

  disco:
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "100M"
    image: slinkgo/disco:0.0.8
    container_name: disco
    ports:
      - "127.0.0.1:8762:8080"
    environment:
#      - DISCO_MAX_CLIENTS=250
      - "DISCO_LIMIT_RATE=1000"
      - "DISCO_LIMIT_BURST=1500"
      - "DISCO_PING_INTERVAL=2s"
      - "DISCO_CLIENT_FAILING_THRESHOLD=3"
      - "DISCO_CLIENT_DOWN_THRESHOLD=4"
      - "DISCO_CLIENT_REMOVE_THRESHOLD=5"
      - "DISCO_USERS=disco:disco"
      - "LOGGING_LEVEL_ROOT=DEBUG"
      - "LOGGING_LEVEL=DEBUG"
    restart: unless-stopped
  eureka:
    image: mvkvl/eureka-server
    container_name: eureka-server
    restart: unless-stopped
    stop_grace_period: "2s"
    environment:
      - "EUREKA_SERVICE_LOGIN=eureka"
      - "EUREKA_SERVICE_PASSWORD=eureka"
#      - "ROOT_LOGGING_LEVEL=WARN"
#      - "CUSTOM_LOGGING_LEVEL=WARN"
#      - "EUREKA_SERVICE_PORT=8761"
#      - "EUREKA_SERVICE_HOSTNAME=localhost"
    ports:
      - "127.0.0.1:8761:8761"
    <<: *basic-log
  gateway-cloud:
    image: mvkvl/cloud-gateway
    container_name: cloud-gateway
    restart: unless-stopped
    stop_grace_period: "2s"
    environment:
      - "SERVER_PORT=8080"
      - "SERVICE_NAME=cloud-gateway"
      - "EUREKA_DEFAULT_ZONE=http://eureka:eureka@eureka:8761/eureka"
    volumes:
      - ./routes:/conf
    ports:
      - "127.0.0.1:9993:8080"
    <<: *basic-log
  eureka-client:
    image: mvkvl/eureka-client
    container_name: eureka-client
    restart: unless-stopped
    stop_grace_period: "2s"
    environment:
      - "CLIENT_SERVER_PORT=8080"
      - "CLIENT_SERVICE_NAME=eureka-client"
#      - "EUREKA_DEFAULT_ZONE=http://eureka:8761/eureka"
      - "EUREKA_DEFAULT_ZONE=http://eureka:eureka@eureka:8761/eureka"
    ports:
      - "127.0.0.1:9990:8080"
    <<: *basic-log
