server:
  port: ${CLIENT_SERVER_PORT:9000}

spring:
  application:
    name: test-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
#        defaultZone: http://eureka:eureka@localhost:9991/eureka
        defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka}
